# Generated by Django 5.0.6 on 2024-06-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('general', 'General Bank'), ('canara', 'Canara Bank'), ('syndicate', 'Syndicate Bank'), ('icici', 'ICICI Bank'), ('axis', 'Axis Bank')], max_length=50)),
                ('check_image', models.ImageField(upload_to='check_images/')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('micr_details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
