# Generated by Django 5.0.6 on 2024-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdata',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
