# Generated by Django 5.0.6 on 2024-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_checkdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdata',
            name='amount',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='checkdata',
            name='amount_in_dg',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
