# Generated by Django 5.0.6 on 2024-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_checkdata_amount_checkdata_amount_in_dg'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdata',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
