# Generated by Django 5.0.6 on 2024-07-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_checkdata_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkdata',
            name='signature',
        ),
        migrations.AddField(
            model_name='checkdata',
            name='signature_present',
            field=models.BooleanField(default=False),
        ),
    ]
