# Generated by Django 5.0.6 on 2024-07-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_remove_checkdata_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdata',
            name='cheque_id',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
