# Generated by Django 5.0.6 on 2024-07-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_checkdata_cheque_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdata',
            name='cheque_id',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
