# Generated by Django 5.0.6 on 2024-07-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_alter_checkdata_cheque_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkdata',
            name='cheque_id',
        ),
    ]
